### ISSUE TITLE
Importing Nodeset fails if it contains a custom NonHierarchicalReference

### ISSUE THREAD

**Issue by thomasfruehwirth** [model-UA/papyrus-opcua-plugin#48]
The Error message shown is "Operation Rolled Back The operation was rolled back because it modified read-only objects: [NonHierarchicalReferences]". I suspect it's a bug. But it could also be a problem in my Nodeset.

Here is the tested Nodeset:
https://github.com/model-UA/uml-to-opcua/blob/master/Uml2OpcuaTransformationTests/DirectedUnnamedAssociation.xml

**Comment by LehrChristoph** [comment]
I looks like the transformation handler tries to modify an element of the Base Nodeset, I will check it asap.

**Comment by LehrChristoph** [comment]
@thomasfruehwirth  FYI: I downloaded the linked NodeSet file and found some errors in it:
- BrowserName and NodeId of the ReferenceType are not set
- referenceType is not set inside a Reference of Class4Type

**Comment by LehrChristoph** [comment]
@thomasfruehwirth  please checkout the linked PR and check if the error still occurs
